
Table MYPAGE_TBL이(가) 삭제되었습니다.


명령의 8 행에서 시작하는 중 오류 발생 -
create table mypage_tbl (
    userId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,  -- 제목, 최대 200자 문자열, 비어 있을 수 없음
    carId varchar2(50) not null,  -- 내용, 최대 2000자 문자열, 비어 있을 수 없음
    carSellName varchar2(50) not null,  -- 작성자, 최대 50자 문자열, 비어 있을 수 없음
    carName varchar2(50) not null,  -- 요청일자, 기본값으로 현재 날짜 사용
    carType varchar2 (10) not null,
    updatedate date default sysdate-- 업데이트일자, 기본값으로 현재 날짜 사용
)
오류 보고 -
ORA-02000: missing ALWAYS keyword
02000. 00000 -  "missing %s keyword"

Sequence SEQ_BOARD이(가) 삭제되었습니다.


명령의 8 행에서 시작하는 중 오류 발생 -
create table mypage_tbl (
    userId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,  -- 제목, 최대 200자 문자열, 비어 있을 수 없음
    carId varchar2(50) not null,  -- 내용, 최대 2000자 문자열, 비어 있을 수 없음
    carSellName varchar2(50) not null,  -- 작성자, 최대 50자 문자열, 비어 있을 수 없음
    carName varchar2(50) not null,  -- 요청일자, 기본값으로 현재 날짜 사용
    carType varchar2 (10) not null,
    updatedate date default sysdate-- 업데이트일자, 기본값으로 현재 날짜 사용
)
오류 보고 -
ORA-02000: missing ALWAYS keyword
02000. 00000 -  "missing %s keyword"

Table MYPAGE_TBL이(가) 삭제되었습니다.


명령의 8 행에서 시작하는 중 오류 발생 -
create table mypage_tbl (
    userId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,  -- 제목, 최대 200자 문자열, 비어 있을 수 없음
    carId varchar2(50) not null,  -- 내용, 최대 2000자 문자열, 비어 있을 수 없음
    carSellName varchar2(50) not null,  -- 작성자, 최대 50자 문자열, 비어 있을 수 없음
    carName varchar2(50) not null,  -- 요청일자, 기본값으로 현재 날짜 사용
    carType varchar2 (10) not null,
    updatedate date default sysdate-- 업데이트일자, 기본값으로 현재 날짜 사용
)
오류 보고 -
ORA-02000: missing ALWAYS keyword
02000. 00000 -  "missing %s keyword"

명령의 18 행에서 시작하는 중 오류 발생 -
alter table mypage_tbl add constraint pk_board primary key(userId)
오류 보고 -
ORA-00942: table or view does not exist
00942. 00000 -  "table or view does not exist"
*Cause:    
*Action:

명령의 8 행에서 시작하는 중 오류 발생 -
create table mypage_tbl (
    userId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,  -- 제목, 최대 200자 문자열, 비어 있을 수 없음
    carId varchar2(50) not null,  -- 내용, 최대 2000자 문자열, 비어 있을 수 없음
    carSellName varchar2(50) not null,  -- 작성자, 최대 50자 문자열, 비어 있을 수 없음
    carName varchar2(50) not null,  -- 요청일자, 기본값으로 현재 날짜 사용
    carType varchar2 (10) not null,
    updatedate date default sysdate-- 업데이트일자, 기본값으로 현재 날짜 사용
)
오류 보고 -
ORA-02000: missing ALWAYS keyword
02000. 00000 -  "missing %s keyword"

명령의 8 행에서 시작하는 중 오류 발생 -
create table mypage_tbl (
    userId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,  -- 제목, 최대 200자 문자열, 비어 있을 수 없음
    carId varchar2(50) not null,  -- 내용, 최대 2000자 문자열, 비어 있을 수 없음
    carSellName varchar2(50) not null,  -- 작성자, 최대 50자 문자열, 비어 있을 수 없음
    carName varchar2(50) not null,  -- 요청일자, 기본값으로 현재 날짜 사용
    carType varchar2 (10) not null,
    updatedate date default sysdate, -- 업데이트일자, 기본값으로 현재 날짜 사용
    CONSTRAINT pk_mypage_tbl PRIMARY KEY (userId)
)
오류 보고 -
ORA-02000: missing ALWAYS keyword
02000. 00000 -  "missing %s keyword"

명령의 8 행에서 시작하는 중 오류 발생 -
CREATE TABLE mypage_tbl (
    userId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    carId VARCHAR2(50) NOT NULL,
    carSellName VARCHAR2(50) NOT NULL,
    carName VARCHAR2(50) NOT NULL,
    carType VARCHAR2(10) NOT NULL,
    updatedate DATE DEFAULT SYSDATE,
    CONSTRAINT pk_mypage_tbl PRIMARY KEY (userId) ALWAYS
)
오류 보고 -
ORA-02000: missing ALWAYS keyword
02000. 00000 -  "missing %s keyword"
